### ISSUE TITLE
Proper error handling for ris live-stream resource

### ISSUE THREAD

**Issue by digizeph** [CAIDA/libbgpstream#117] opened 2019-07-12 18:16 UTC
Example as follows:
```
HTTP ERROR: Transferred a partial file (18)
2019-07-12 11:02:19 27191: bs_format_rislive.c:380: ERROR: JSON parser returned -3
2019-07-12 11:02:19 27191: bs_format_rislive.c:299: WARNING: corrupted ris-stream message: {"type":"ris_message","data":{"timestamp":1562954418.09,"peer":"2001:7f8:1::a501:2859:1","peer_asn":"12859","id":"2001:7f8:1::a501:2859:1-1562954418.09-34138224","raw":"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0072020000005B4001010040020E02030000323B00001B1B0000002A80040400000000C0080C323B03E8323B044C323B0681900E002C00020120200107F8000100000000A50128590001FE8000000000000046F47701F5BD9BDF00302620017100EF","host":"rrc03","type":"UPDATE","path":[12859,6939,42],"community":[[12859,1000],[12859,1100],[12859,1665
```

**Comment by alistairking** [comment] 2019-07-18 17:08
Duplicate of #116

**Closed by alistairking** 2019-07-18 17:08 UTC
